name: reper
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  cached_network_image: ^3.3.1
  calendar_date_picker2: ^0.5.3
  cloud_firestore: ^4.15.2
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  easy_localization: ^3.0.3
  firebase_auth: ^4.17.2
  firebase_core: ^2.25.2
  firebase_storage: ^11.6.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_chord: ^0.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.4.9
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.0
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  lottie: ^3.0.0
  package_info_plus: ^6.0.0
  toggle_switch: ^2.1.0
  transparent_image: ^2.0.1
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/img/rippy-logo.png"
  ios: true
  android: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/loaders/
    - assets/translations/
    - assets/animations/
