name: reper
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.2
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  firebase_auth: ^4.17.2
  firebase_core: ^2.25.2
  firebase_storage: ^11.6.3
  flutter:
    sdk: flutter
  flutter_chord: ^0.1.2
  flutter_riverpod: ^2.4.9
  gallery_picker: ^0.4.8
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  transparent_image: ^2.0.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/loaders/
    - assets/translations/
